### PR TITLE
Fix for Dancer2 >= 0.149000_01

### PR DESCRIPTION
**Pull request by xsawyerx**
This should make it work for Dancer2 >= 0.149000_01.

Unfortunately it's not released yet. Would it be possible to release a dev release of this? It could be updated along with Dancer2, which will probably see a stable coming in the next week or two - or do you prefer to wait?

### CODE REVIEW

**Comment by xsawyerx** [comment]
I'm actually not sure _at all_ why that single commit appears below all of those commits. I'm based off master...

**Comment by yanick** [comment]
Argh. Yup, you did the right thing. The gotcha is that the official repo is now under perldancer. My bad, I should have cleanly removed this instance.

In any case, got the patch. I'll craft and send off to CPAN a dev release in a few minutes.

**Comment by yanick** [comment]
Merged, trial version sent to CPAN. Enjoy! :-)

**Comment by xsawyerx** [comment]
Thank you!

In my sleep-deprived state, I realized I probably should have depended on the release that changed this behavior so people wouldn't run this new version on an older Dancer version.

**Pull request closed without merging**
